---
title: "Replication of 'The relationship between future time perspective and memory control beliefs in older adults' by Sarah Barber and Carla Strickland-Hughes (2019, Research in Human Development)" 
author: "Kathrine Whitman (kwhitman@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Links to github repo 
### Link to repo https://github.com/psych251/barber2019/tree/main
###Link to orignal paper https://github.com/psych251/barber2019/tree/main/original_paper
## Introduction

I chose to examine this study because it bridges key themes in my research: lifespan development, future time perspectives, beliefs about memory and self-efficacy, and implications for cognitive aging. By disentangling three possible components of future time perspective (FTP) (coded in this study as opportunity, extension, and constraint), the study provides a detailed framework for understanding how older adults’ views of their future shape their beliefs about memory control. These findings are interesting in developing a better understanding the role of time horizons in human motivation, as it highlights that not all aspects of FTP influence individual's beliefs equally. Similar to how some subscales of the Ryff Psychological well-being scales map onto age-related changes in well-being, subscales of the FTP scale might apply differently by age. In particular, the strong link between FTP-opportunity and adaptive memory beliefs suggests that motivation and sense of control may be better associated with cognitive outcomes in late-life. 

## Methods
The original study recruited 189 community-dwelling older adults aged 60–85 who completed an online survey. Stimuli consisted of standardized self-report measures: the Carstensen & Lang FTP Scale, divided into the three subscales validated by Rohr et al. (2017); the Adolescent and Adult Time Inventory – Future Attitudes subscales to assess positive and negative future outlooks; the Life Progress Slider (adapted from Cottle’s Future Extension Line) to gauge perceived position in the lifespan; and the Memory Controllability Inventory to assess beliefs about potential improvement, inevitable decline, and effort utility for memory. All responses were collected using Likert-type or slider scales. 

Survey materials and administration are accessible; however, it should be noted that the participants in this online sample had high education levels, with 12% of participants having an MD or PhD. In our analysis, we will control for education and determine if education levels effect memory control beliefs and future time perspectives. 

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
